import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useRef } from 'react'
import { trpc } from '../utils/trpc'
// import { prisma } from '../server/db/client'

const QuestionCreator: React.FC = () => {
  const inputRef = useRef<HTMLInputElement>(null)
  const client = trpc.useContext()
  const { mutate, isLoading } = trpc.useMutation('questions.create', {
    onSuccess: (data) => {
      console.log('success data: ', data)
      client.invalidateQueries(['questions.getAll'])
      if (!inputRef.current) return
      inputRef.current.value = ''
    },
  })

  return (
    <input
      ref={inputRef}
      disabled={isLoading}
      type="text"
      className="my-6 p-2 text-center border-2 w-1/3"
      onKeyDown={(e) => {
        if (e.key === 'Enter') {
          mutate({ question: e.currentTarget.value })
          e.currentTarget.value = ''
        }
      }}
    />
  )
}

const Home: NextPage = () => {
  const { data } = trpc.useQuery(['questions.getAll'])
  // console.log('---- ', data)

  return (
    <>
      <Head>
        <title>Voting App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        {/* <p className="text-2xl text-gray-700">{data?.questions[1]?.question}</p> */}

        {data ? (
          data.map((q) => (
            <Link href={`/question/${q.id}`} key={q.id}>
              <a>
                <p className=" mb-2 text-xl text-blue-500 hover:text-blue-700 motion-safe:hover:scale-105 duration-300">
                  {q.question}
                </p>
              </a>
            </Link>
          ))
        ) : (
          <p className="animate-bounce">Loading..</p>
        )}

        <QuestionCreator />
      </main>
    </>
  )
}

// export const getServerSideProps = async () => {
//   const questions = await prisma.pollQuestion.findMany()

//   return {
//     props: {
//       questions: JSON.stringify(questions),
//     },
//   }
// }

export default Home
